export const headCells = [
  {
    id: 'id',
    numeric: true,
    disablePadding: false,
    label: 'ID',
  },
  {
    id: 'photo',
    numeric: false,
    disablePadding: false,
    label: 'Photo',
  },
  {
    id: 'startDate',
    numeric: false,
    disablePadding: false,
    label: 'Start date',
  },
  {
    id: 'endDate',
    numeric: false,
    disablePadding: false,
    label: 'End date',
  },
  {
    id: 'eventType',
    numeric: false,
    disablePadding: false,
    label: 'Event type',
  },
  {
    id: 'title',
    numeric: false,
    disablePadding: false,
    label: 'Title',
  },
  {
    id: 'description',
    numeric: false,
    disablePadding: false,
    label: 'Description',
  },
  {
    id: 'location',
    numeric: false,
    disablePadding: false,
    label: 'Location',
  },
  {
    id: 'isRegistrable',
    numeric: false,
    disablePadding: false,
    label: 'Is registrable',
  },
  {
    id: 'registrableLink',
    numeric: false,
    disablePadding: false,
    label: 'Registrable link',
  },
  {
    id: 'ageRestriction',
    numeric: false,
    disablePadding: false,
    label: 'Age restriction',
  },
  {
    id: 'action',
    numeric: false,
    disablePadding: false,
    label: 'Action',
  }
];
  
export const eventRows = [
  {
    id: 1,
    photo: "https://eventbrite-s3.s3.amazonaws.com/marketing/landingpages/assets/2023/organizer/a_organizer_event--creator-eventbrite-.jpeg",
    startDate: "SUN. APR 23",
    endDate: "SUN. APR 23",
    eventType: "COMMUNITY",
    title: "NSF SPRING FLING AT THE ZOO",
    description: "Lorem ipsum dolor sit amet consectetur. Tincidunt morbi pellentesque eget diam...",
    location: "Norfolk, VA",
    isRegistrable: "No",
    registrableLink: "N/A",
    ageRestriction: "N/A",
  },
  {
    id: 2,
    photo: "https://www.aleitevents.com/wp-content/uploads/2019/02/ABCF1-19-scaled.jpg",
    startDate: "MON. APR 23",
    endDate: "TUE. APR 24",
    eventType: "FUNDRAISING",
    title: "DALLAS evening of tribute",
    description: "Lorem ipsum dolor sit amet consectetur. Tincidunt morbi pellentesque eget diam...",
    location: "Dallas, TX",
    isRegistrable: "Yes",
    registrableLink: "https://i.guim.co.uk/img/media/b60a4e5fed7d577aaaae08c2f194ad432732b073/0_0_5333_3200/master/5333.jpg?width=620&dpr=2&s=none",
    ageRestriction: "N/A",
  },
  {
    id: 3,
    photo: "https://www.aleitevents.com/wp-content/uploads/2019/02/HGGYearendALL-062-scaled-1.jpg",
    startDate: "SUN. JUN 18",
    endDate: "FRI. JUN 23",
    eventType: "CAMP",
    title: "CaMP SPECOPS 1",
    description: "Lorem ipsum dolor sit amet consectetur. Tincidunt morbi pellentesque eget diam...",
    location: "Eastern Shore, VA",
    isRegistrable: "Yes",
    registrableLink: "https://i.guim.co.uk/img/media/b60a4e5fed7d577aaaae08c2f194ad432732b073/0_0_5333_3200/master/5333.jpg?width=620&dpr=2&s=none",
    ageRestriction: "14-17 yrs",
  },
];
