export const headCells = [
  {
    id: 'id',
    numeric: true,
    disablePadding: false,
    label: 'ID',
  },
  {
    id: 'name',
    numeric: false,
    disablePadding: false,
    label: 'Username',
  },
  {
    id: 'status',
    numeric: false,
    disablePadding: false,
    label: 'Status',
  },
  {
    id: 'email',
    numeric: false,
    disablePadding: false,
    label: 'Email',
  },
  {
    id: 'age',
    numeric: true,
    disablePadding: false,
    label: 'Age',
  },
  {
    id: 'action',
    numeric: false,
    disablePadding: false,
    label: 'Action',
  }
];

export const userRows = [
  {
    id: 1,
    name: "Snow",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 2,
    name: "Jamie Lannister",
    status: "passive",
    email: "2snow@gmail.com",
    age: 42,
  },
  {
    id: 3,
    name: "Lannister",
    status: "pending",
    email: "3snow@gmail.com",
    age: 45,
  },
  {
    id: 4,
    name: "Stark",
    status: "active",
    email: "4snow@gmail.com",
    age: 16,
  },
  {
    id: 5,
    name: "Targaryen",
    status: "passive",
    email: "5snow@gmail.com",
    age: 22,
  },
  {
    id: 6,
    name: "Melisandre",
    status: "active",
    email: "6snow@gmail.com",
    age: 15,
  },
  {
    id: 7,
    name: "Clifford",
    status: "passive",
    email: "7snow@gmail.com",
    age: 44,
  },
  {
    id: 8,
    name: "Frances",
    status: "active",
    email: "8snow@gmail.com",
    age: 36,
  },
  {
    id: 9,
    name: "Roxie",
    status: "pending",
    email: "snow@gmail.com",
    age: 65,
  },
  {
    id: 10,
    name: "Emma",
    status: "active",
    email: "emma@gmail.com",
    age: 65,
  },
  {
    id: 11,
    name: "Ethan",
    status: "active",
    email: "ethan@gmail.com",
    age: 65,
  },
  {
    id: 12,
    name: "Olivia",
    status: "active",
    email: "olivia@gmail.com",
    age: 65,
  },
  {
    id: 13,
    name: "Liam",
    status: "active",
    email: "liam@gmail.com",
    age: 65,
  },
  {
    id: 14,
    name: "Isabella",
    status: "active",
    email: "isabella@gmail.com",
    age: 65,
  },
  {
    id: 15,
    name: "Mia",
    status: "active",
    email: "mia@gmail.com",
    age: 65,
  },
];
